export const IDL: Record<string, any> = {
  address: "GSeGuv2K3meepgSHCehP5jGkRnjRZk96a9vsPSSJ7TjC",
  metadata: {
    name: "latamlink_pay",
    version: "0.1.0",
    spec: "0.0.1",
    description: "",
  },
  version: "0.1.0",
  name: "latamlink_pay",
  constants: [
    { name: "MAX_DESTINATIONS", type: "u8", value: "10" },
    { name: "MAX_TERMINAL_ID_LEN", type: "u8", value: "32" },
  ],
  instructions: [
    {
      name: "initializeMerchant",
      discriminator: [244, 62, 129, 69, 59, 110, 90, 52],
      accounts: [
        { name: "owner", isMut: true, isSigner: true },
        { name: "merchant", isMut: true, isSigner: false },
        { name: "paymentTokenMint", isMut: false, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "gasVault", isMut: true, isSigner: false },
        { name: "destination0", isMut: true, isSigner: false },
        { name: "destination1", isMut: true, isSigner: false },
        { name: "destination2", isMut: true, isSigner: false },
        { name: "destination3", isMut: true, isSigner: false },
        { name: "destination4", isMut: true, isSigner: false },
        { name: "destination5", isMut: true, isSigner: false },
        { name: "destination6", isMut: true, isSigner: false },
        { name: "destination7", isMut: true, isSigner: false },
        { name: "destination8", isMut: true, isSigner: false },
        { name: "destination9", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [
        { name: "merchantId", type: "u64" },
        { name: "feeBps", type: "u16" },
        { name: "posFeeBps", type: "u16" },
        { name: "minPaymentAmount", type: "u64" },
        { name: "destinationsCount", type: "u8" },
        { name: "percentages", type: { array: ["u8", 10] } },
        { name: "posTerminalId", type: "string" },
      ],
    },
    {
      name: "updateConfig",
      discriminator: [102, 77, 158, 235, 28, 216, 191, 121],
      accounts: [
        { name: "owner", isMut: false, isSigner: true },
        { name: "merchant", isMut: true, isSigner: false },
        { name: "destination0", isMut: true, isSigner: false },
        { name: "destination1", isMut: true, isSigner: false },
        { name: "destination2", isMut: true, isSigner: false },
        { name: "destination3", isMut: true, isSigner: false },
        { name: "destination4", isMut: true, isSigner: false },
        { name: "destination5", isMut: true, isSigner: false },
        { name: "destination6", isMut: true, isSigner: false },
        { name: "destination7", isMut: true, isSigner: false },
        { name: "destination8", isMut: true, isSigner: false },
        { name: "destination9", isMut: true, isSigner: false },
      ],
      args: [
        { name: "feeBps", type: "u16" },
        { name: "posFeeBps", type: "u16" },
        { name: "minPaymentAmount", type: "u64" },
        { name: "destinationsCount", type: "u8" },
        { name: "percentages", type: { array: ["u8", 10] } },
      ],
    },
    {
      name: "toggleMerchantActive",
      discriminator: [85, 104, 169, 138, 158, 207, 17, 75],
      accounts: [
        { name: "owner", isMut: false, isSigner: true },
        { name: "merchant", isMut: true, isSigner: false },
      ],
      args: [],
    },
    {
      name: "pay",
      discriminator: [119, 18, 216, 65, 192, 117, 122, 220],
      accounts: [
        { name: "payer", isMut: true, isSigner: true },
        { name: "payerTokenAccount", isMut: true, isSigner: false },
        { name: "merchant", isMut: true, isSigner: false },
        { name: "paymentTokenMint", isMut: false, isSigner: false },
        { name: "posFeeDestination", isMut: true, isSigner: false },
        { name: "vault", isMut: true, isSigner: false },
        { name: "gasVault", isMut: true, isSigner: false },
        { name: "destination0", isMut: true, isSigner: false },
        { name: "destination1", isMut: true, isSigner: false },
        { name: "destination2", isMut: true, isSigner: false },
        { name: "destination3", isMut: true, isSigner: false },
        { name: "destination4", isMut: true, isSigner: false },
        { name: "destination5", isMut: true, isSigner: false },
        { name: "destination6", isMut: true, isSigner: false },
        { name: "destination7", isMut: true, isSigner: false },
        { name: "destination8", isMut: true, isSigner: false },
        { name: "destination9", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
        { name: "systemProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
    {
      name: "withdrawGasFees",
      discriminator: [157, 179, 70, 131, 34, 104, 36, 6],
      accounts: [
        { name: "owner", isMut: false, isSigner: true },
        { name: "merchant", isMut: false, isSigner: false },
        { name: "gasVault", isMut: true, isSigner: false },
        { name: "destination", isMut: true, isSigner: false },
        { name: "tokenProgram", isMut: false, isSigner: false },
      ],
      args: [{ name: "amount", type: "u64" }],
    },
  ],
  accounts: [
    {
      name: "Merchant",
      discriminator: [71, 235, 30, 40, 231, 21, 32, 64],
      type: { defined: { name: "Merchant" } },
    },
  ],
  types: [
    {
      name: "Merchant",
      type: {
        kind: "struct",
        fields: [
          { name: "owner", type: "pubkey" },
          { name: "paymentTokenMint", type: "pubkey" },
          { name: "merchantId", type: "u64" },
          { name: "posTerminalId", type: "string" },
          { name: "destinations", type: { vec: "pubkey" } },
          { name: "percentages", type: { vec: "u8" } },
          { name: "feeBps", type: "u16" },
          { name: "posFeeBps", type: "u16" },
          { name: "minPaymentAmount", type: "u64" },
          { name: "bump", type: "u8" },
          { name: "isActive", type: "bool" },
          { name: "totalPaymentsReceived", type: "u64" },
          { name: "totalVolume", type: "u64" },
        ],
      },
    },
    {
      name: "MerchantInitialized",
      type: {
        kind: "struct",
        fields: [
          { name: "merchant", type: "pubkey" },
          { name: "owner", type: "pubkey" },
          { name: "merchantId", type: "u64" },
          { name: "posTerminalId", type: "string" },
          { name: "destinationsCount", type: "u8" },
          { name: "feeBps", type: "u16" },
          { name: "posFeeBps", type: "u16" },
          { name: "minPaymentAmount", type: "u64" },
        ],
      },
    },
    {
      name: "ConfigUpdated",
      type: {
        kind: "struct",
        fields: [
          { name: "merchant", type: "pubkey" },
          { name: "destinationsCount", type: "u8" },
          { name: "feeBps", type: "u16" },
          { name: "posFeeBps", type: "u16" },
          { name: "minPaymentAmount", type: "u64" },
        ],
      },
    },
    {
      name: "PaymentProcessed",
      type: {
        kind: "struct",
        fields: [
          { name: "merchant", type: "pubkey" },
          { name: "payer", type: "pubkey" },
          { name: "posTerminalId", type: "string" },
          { name: "amount", type: "u64" },
          { name: "posFee", type: "u64" },
          { name: "gasFee", type: "u64" },
          { name: "dust", type: "u64" },
          { name: "splitAmounts", type: { vec: "u64" } },
          { name: "timestamp", type: "i64" },
        ],
      },
    },
    {
      name: "GasFeesWithdrawn",
      type: {
        kind: "struct",
        fields: [
          { name: "merchant", type: "pubkey" },
          { name: "owner", type: "pubkey" },
          { name: "amount", type: "u64" },
          { name: "timestamp", type: "i64" },
        ],
      },
    },
  ],
  events: [
    {
      name: "MerchantInitialized",
      discriminator: [96, 0, 189, 109, 128, 70, 106, 89],
      fields: [
        { name: "merchant", type: "pubkey", index: false },
        { name: "owner", type: "pubkey", index: false },
        { name: "merchantId", type: "u64", index: false },
        { name: "posTerminalId", type: "string", index: false },
        { name: "destinationsCount", type: "u8", index: false },
        { name: "feeBps", type: "u16", index: false },
        { name: "posFeeBps", type: "u16", index: false },
        { name: "minPaymentAmount", type: "u64", index: false },
      ],
    },
    {
      name: "ConfigUpdated",
      discriminator: [40, 241, 230, 122, 11, 19, 198, 194],
      fields: [
        { name: "merchant", type: "pubkey", index: false },
        { name: "destinationsCount", type: "u8", index: false },
        { name: "feeBps", type: "u16", index: false },
        { name: "posFeeBps", type: "u16", index: false },
        { name: "minPaymentAmount", type: "u64", index: false },
      ],
    },
    {
      name: "PaymentProcessed",
      discriminator: [22, 109, 191, 213, 83, 63, 120, 219],
      fields: [
        { name: "merchant", type: "pubkey", index: false },
        { name: "payer", type: "pubkey", index: false },
        { name: "posTerminalId", type: "string", index: false },
        { name: "amount", type: "u64", index: false },
        { name: "posFee", type: "u64", index: false },
        { name: "gasFee", type: "u64", index: false },
        { name: "dust", type: "u64", index: false },
        { name: "splitAmounts", type: { vec: "u64" }, index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
    {
      name: "GasFeesWithdrawn",
      discriminator: [41, 190, 111, 128, 66, 185, 252, 250],
      fields: [
        { name: "merchant", type: "pubkey", index: false },
        { name: "owner", type: "pubkey", index: false },
        { name: "amount", type: "u64", index: false },
        { name: "timestamp", type: "i64", index: false },
      ],
    },
  ],
  errors: [
    { code: 6000, name: "InvalidPercentages", msg: "Porcentajes no suman 100" },
    { code: 6001, name: "InvalidFee", msg: "Fee > 100%" },
    { code: 6002, name: "MinPaymentRequired", msg: "Pago menor al mínimo" },
    { code: 6003, name: "Unauthorized", msg: "No autorizado" },
    { code: 6004, name: "DestinationsCountMismatch", msg: "Destinos/porcentajes no coinciden" },
    { code: 6005, name: "DestinationsEmpty", msg: "Destinos vacíos" },
    { code: 6006, name: "TooManyDestinations", msg: "Máximo 10 destinos" },
    { code: 6007, name: "InvalidDestinationAccount", msg: "Cuenta destino inválida" },
    { code: 6008, name: "InvalidMint", msg: "Mint incorrecto" },
    { code: 6009, name: "DestinationCannotBeVault", msg: "Destino no puede ser vault" },
    { code: 6010, name: "DestinationCannotBeGasVault", msg: "Destino no puede ser gas vault" },
    { code: 6011, name: "InsufficientGasVaultBalance", msg: "Fondos insuficientes" },
    { code: 6012, name: "DuplicateDestination", msg: "Destinos duplicados" },
    { code: 6013, name: "InvalidMinPayment", msg: "Monto mínimo inválido" },
    { code: 6014, name: "InvalidAmount", msg: "Monto inválido" },
    { code: 6015, name: "MerchantInactive", msg: "Comercio inactivo" },
    { code: 6016, name: "MathOverflow", msg: "Error aritmético" },
    { code: 6017, name: "InvalidParameter", msg: "Parámetro inválido" },
  ],
}
